### ISSUE TITLE
Filter button is missing

### ISSUE THREAD

**Issue by wdch-nseeley** [call-a3/slack-filter-bots#1]
The per-channel filter button is now missing.  This problem looks like a CSS or icon issue, because the mouse cursor changes to a pointer when hovering and the button is still clickable (operable).

Chrome 42.0.2311.152 m

**Comment by call-a3** [comment]
Confirmed.

Seems slack changed there iconset. I'm on it, expect a fix within 24 hours.

**Comment by call-a3** [comment]
Should be fixed in 7f62431f0d3e460b23e34b87a9bcb27fca0edaba.

**Comment by wdch-nseeley** [comment]
I just got the update.  Its working great!  Thanks.
