### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by jrmgx** [call-a3/slack-filter-bots#13]
Hello I'm working on a similar extension, maybe we can talk to join our force?
I let you check it out my version here: https://jerome.gangneux.net/projects/2017-01-filter-for-slack/

**Comment by call-a3** [comment]
Sure, that could be great. I looked at your GitHub profile but didn't see any code for your extension. Is there somewhere I can have a look at some of your code?

**Comment by jrmgx** [comment]
Hello, this is my code: https://github.com/jrmgx/filter-for-slack
have a look and tell me what you think :)

**Comment by DownUnderMan** [comment]
The links above do not work. Is there a way to specify a search term for the filter? i.e. only display messages with a #term or keyword?

**Comment by jrmgx** [comment]
This has been discontinued, sorry.
Have a good day
