### ISSUE TITLE
Filter button has moved

### ISSUE THREAD

**Issue by wdch-nseeley** [call-a3/slack-filter-bots#2]
The Slack layout seems to have changed slightly as the Filter button no longer positions left of the Channel Info button. The button can now be found just below the channel name.

**Comment by call-a3** [comment]
Thanks for reporting this! I'll look into it :)

**Comment by call-a3** [comment]
Should be fixed.
The new release should show up in the next hour and applied automatically to your browser.
If this doesn't fix it, please update this issue.

Thanks for using slack-filter-bots!

**Comment by wdch-nseeley** [comment]
Sorry to trouble you, but thanks for fixing it.
This should help new users immensely!

**Comment by call-a3** [comment]
No problem ;) Happy to help!
