### ISSUE TITLE
Where's the filter button?

### ISSUE THREAD

**Issue by nshenry03** [call-a3/slack-filter-bots#3]
Sorry, I'm sure it's there somewhere, but I don't see the button to filter a IFTTT bot...  I looked in the top right of the browser, in the IFTTT slack message itself and the gear icon to the top right of the message, I looked at the top of the channel... Unfortunately still don't see how to filter bots...  Any suggestions of where to look and/or screenshots would be super helpful.  Thanks!
![toprightbrowser](https://cloud.githubusercontent.com/assets/465952/10551930/5c3a08d0-740d-11e5-84df-8bac2a451c8f.png)

**Comment by call-a3** [comment]
Hi! You pointed me to a valid issue. There are clear screenshots in the [chrome web store](https://chrome.google.com/webstore/detail/slack-bot-filter/blephhkggdennbfmdcjmlfimedknghfc), however: these date from an older version where the filter button had a different icon. 

You're looking for a button with an eye-symbol in the same place where the old button used to be.
That's on the top-right of the slack channel itself, next to the button that shows channel members.

**Comment by nshenry03** [comment]
Found it, thanks @call-a3
