### ISSUE TITLE
Not working, and broken icon?

### ISSUE THREAD

**Issue by krotkruton** [call-a3/slack-filter-bots#4]
Two issues

1.  The icon seems to be broken.  This is what it looks like when it's on (I think).  If I click it, it turns grey looks like half of an eye, based on the other problem thread.
![image](https://cloud.githubusercontent.com/assets/6580952/10823279/ea9e0a16-7e28-11e5-979d-91b094269483.png)

2.  The slackbot messages are not being filtered.  I've tried toggling the button in both directions, and the messages remain.  I believe slack updated recently, so maybe they changed something that prevents filtering?

**Comment by call-a3** [comment]
I can't reproduce this on my machine. What browser/OS are you using?
With regards to only half the icon being shown, what is your screen resolution?

**Comment by krotkruton** [comment]
[image: slackbot.PNG]

I'm using Chrome on Windows Server 2008 R2.  Above is a picture of exactly
what it's doing.  I believe that's a shut eye so that mean it shouldn't be
showing up.

With the half icon, it's weird because I get different portions of the icon
in different channels.  2560x1600 on one monitor and 1920x1080 on another,
and it behaves the same way on both.

**Comment by dbowman410** [comment]
I don't have the partial icon problem, but the add-on stopped filtering BOT message quite a while ago. The icon toggles between the blue closed eye and gray open eye, but nothing is filtered. Used to work fine. Windows 10, Chrome 48.0.2564.48 beta-m (64-bit).

**Comment by Marthym** [comment]
Same problem since november slack update

**Comment by call-a3** [comment]
I tried to respond on new years eve, but apparantly my e-mail got lost or wasn't sent... Anyhow...

I have been notified of this issue one week ago. When Slack makes changes this sometimes breaks the extension. I use the desktop app so I don't always notice when this happens. During the holidays I was a bit too busy to take care of this, but now I have a new version out which should fix things. Please notify me if this is not the case!!

**Comment by Marthym** [comment]
I thank you for your response.
I have make some pull request which fix the problem and add some other stuff. I currently use it in my chrome and it seem to fix the problem.

**Comment by dbowman410** [comment]
I can also confirm that v0.2.5 fixes the issue for me. Thank you.
